spring.application.name=code-runner

spring.datasource.url=jdbc:postgresql://localhost:5432/codejudge
spring.datasource.username=christian
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
